"""Add name field to agent model

Revision ID: 718a644abc08
Revises: 58c8a4fa6527
Create Date: 2023-11-12 21:12:23.798820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718a644abc08'
down_revision: Union[str, None] = '58c8a4fa6527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'agent', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent', type_='unique')
    op.drop_column('agent', 'name')
    # ### end Alembic commands ###
