"""Add Task project_id index

Revision ID: 745e07c0d9b6
Revises: 608a6f9fce76
Create Date: 2023-11-13 21:15:06.702731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745e07c0d9b6'
down_revision: Union[str, None] = '608a6f9fce76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    # ### end Alembic commands ###
