version: '3.8'
services:
  migrations:
    build: .
    command: sleep 5 && alembic upgrade head
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname

  api:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    volumes:
      - .:/app
    ports:
      - "8000:80"
    depends_on:
      - migrations
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
